[package]
org = "tharanawanigaratne"
name = "tool_scan"
version = "0.0.7"
distribution = "2201.9.1"
authors = ["tharanawanigaratne"]
keywords = ["scan", "static code analysis"]
license = ["Apache-2.0"]
repository = "https://github.com/Xenowa/static-code-analysis-tool/"
