[package]
org = "tharanawanigaratne"
name = "tool_scan"
version = "0.0.3"
distribution = "2201.9.0"
authors = ["Tharana"]
keywords = ["scan", "static code analysis"]
license = ["Apache-2.0"]
repository = "https://github.com/Xenowa/static-code-analysis-tool"
